<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

?>
<div class="wrap" id="suma-wrap">
    <div class="suma-content">
        <div class="suma-heading">
            <img src="<?php echo SUMEDIA_PLUGIN_URL . 'sumedia-base/assets/images/kolibri-logo.png'; ?>" alt="Sumedia" />
            <h1><?php echo __('Sumedia Plugins', 'sumedia-base'); ?> <small>&ndash; <?php echo __('Plugin Overview', 'sumedia-base'); ?></small></h1>
        </div>
    </div>

    <div class="wrap suma-content">
        <div class="suma-overview-plugins">
            <?php foreach ($this->get('plugins')->get_plugins() as $plugin) : ?>
                <div class="suma-overview-plugin">
                    <?php require $plugin['description_template']; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>