<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

$plugins = $this->get('sumedia_base_admin_view_plugins');

?>
<div class="wrap suma-content">
    <div class="suma-overview-plugins">
        <?php foreach ($plugins->plugins as $plugin) : ?>
            <div class="suma-overview-plugin">
                <?php require $plugin['description_template']; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>